#ifndef _STACKSPACE_H_
#define _STACKSPACE_H_

#include "portmacro.h"

#define TASKIMU_STACKSPACE 400
#define TASKCOMMANDHANDLER_STACKSPACE 300
#define TASKDRIVE_STACKSPACE 1000
#define TASKIMUMAGSCALING_STACKSPACE 300
#define TASKINPUTBUFFER_STACKSPACE 500
#define TASKLED_STACKSPACE configMINIMAL_STACK_SIZE

#endif /* _STACKSPACE_H_ */
